# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('CU', 'Flokken'), ('PI', 'Pionerene'), ('SC', 'Troppen'), ('RO', 'Roverlag'), ('LE', 'Leder'), ('FR', 'Venn')], default='SC', max_length=2)),
                ('attending', models.BooleanField(default='true')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_dt', models.DateTimeField(verbose_name='event start')),
                ('end_dt', models.DateTimeField(verbose_name='event end')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
