# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='contact_email',
            new_name='main_contact_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='contact_phone',
            new_name='main_contact_phone',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='alt_contact_email',
            field=models.EmailField(default='x@x.x', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='alt_contact_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='alt_contact_phone',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='main_contact_email',
            field=models.EmailField(default='x@x.x', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
