# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171109_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='notes',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
    ]
