# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attendee_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
