# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='alt_contact_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='alt_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='alt_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
