# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171109_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
