# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='main_contact_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='main_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='main_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
