# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171110_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.CharField(default='x@x.x', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contact_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
    ]
