# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20171111_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
