# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_deadline_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billed',
            field=models.BooleanField(default=False, help_text="Set true if we're going to send out a bill/faktura, false if we are going to accept cash/vipps/etc"),
        ),
    ]
